version: '3'

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    command:  npm run start
    volumes:
      - ./frontend/src:/usr/src/app/src
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    command: npm run dev
    volumes:
      - ./api/src:/usr/src/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
  auth:
    command: npm run dev
    volumes:
      - ./auth/src:/usr/src/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
  nginx:
    volumes:
      - ./nginx/nginx.dev.nginx:/etc/nginx/conf.d/nginx.conf
